CREATE TABLE "USER1"."T1"(
a int, 
b int, 
c int
)
TABLESPACE TS1;

CREATE TABLE "USER2"."T2"(
a int, 
b int, 
c int
)
TABLESPACE TS1;

 CREATE TABLE "USER3"."T3"(
a int, 
b int, 
c int
)
TABLESPACE TS1;

 CREATE TABLE "USER4"."T4"(
a int, 
b int, 
c int
)
TABLESPACE TS2;

 CREATE TABLE "USER5"."T5"(
a int, 
b int, 
c int
)
TABLESPACE TS2;
 CREATE TABLE "USER6"."T6"(
a int, 
b int, 
c int
)
TABLESPACE TS2;

insert into USER1.T1 values(1,2,3);
insert into USER2.T2 values(4,6,8);
insert into USER3.T3 values(9,12,15);
insert into USER4.T4 values(16,20,24);
insert into USER5.T5 values(25,30,35);
insert into USER6.T6 values(36,42,48);	
commit;	

CREATE USER RMAN_user IDENTIFIED BY rman
DEFAULT TABLESPACE RMAN
QUOTA UNLIMITED ON SYSTEM;

GRANT ALL PRIVILEGES TO RMAN;
GRANT RECOVERY_CATALOG_OWNER TO RMAN_user;
GRANT CONNECT, RESOURCE TO RMAN_user;


CREATE USER USER1 IDENTIFIED BY USER1
DEFAULT TABLESPACE TS1
QUOTA UNLIMITED ON TS1;

GRANT ALL PRIVILEGES TO USER1;

CREATE USER USER2 IDENTIFIED BY USER2
DEFAULT TABLESPACE TS1
QUOTA UNLIMITED ON TS1;

GRANT ALL PRIVILEGES TO USER2;

CREATE USER USER3 IDENTIFIED BY USER3
DEFAULT TABLESPACE TS1
QUOTA UNLIMITED ON TS1;

GRANT ALL PRIVILEGES TO USER3;

CREATE USER USER4 IDENTIFIED BY USER4
DEFAULT TABLESPACE TS2
QUOTA UNLIMITED ON TS2;

GRANT ALL PRIVILEGES TO USER4;

CREATE USER USER5 IDENTIFIED BY USER5
DEFAULT TABLESPACE TS2
QUOTA UNLIMITED ON TS2;

GRANT ALL PRIVILEGES TO USER5;

CREATE USER USER6 IDENTIFIED BY USER6
DEFAULT TABLESPACE TS2
QUOTA UNLIMITED ON TS2;

GRANT ALL PRIVILEGES TO USER6;


CREATE OR REPLACE FUNCTION logdata
  RETURN SYS_REFCURSOR
AS
  datos SYS_REFCURSOR;
BEGIN
  OPEN datos FOR SELECT USERNAME AS usr,(XIDUSN || '.' || XIDSLT || '.' || XIDSQN) as XID, SQL_REDO 
                    FROM V$LOGMNR_CONTENTS 
                    WHERE SEG_OWNER IS NULL OR SEG_OWNER NOT IN ('SYS', 'SYSTEM');
return datos;
END;
/
