# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Patterns.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 585)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.search = QtWidgets.QPushButton(self.groupBox)
        self.search.setObjectName("search")
        self.gridLayout_2.addWidget(self.search, 0, 2, 1, 1)
        self.chooser = QtWidgets.QComboBox(self.groupBox)
        self.chooser.setObjectName("chooser")
        self.chooser.addItem("")
        self.chooser.addItem("")
        self.chooser.addItem("")
        self.chooser.addItem("")
        self.chooser.addItem("")
        self.chooser.addItem("")
        self.chooser.addItem("")
        self.chooser.addItem("")
        self.gridLayout_2.addWidget(self.chooser, 0, 1, 1, 1)
        self.filter = QtWidgets.QLineEdit(self.groupBox)
        self.filter.setObjectName("filter")
        self.gridLayout_2.addWidget(self.filter, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 2, 5, 1, 1)
        self.loadButton = QtWidgets.QPushButton(self.groupBox)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout_2.addWidget(self.loadButton, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 4, 1, 1)
        self.graphics = QtWidgets.QTabWidget(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.graphics.setFont(font)
        self.graphics.setAutoFillBackground(False)
        self.graphics.setObjectName("graphics")
        self.tab_user = QtWidgets.QWidget()
        self.tab_user.setObjectName("tab_user")
        self.userLabel = QtWidgets.QLabel(self.tab_user)
        self.userLabel.setGeometry(QtCore.QRect(-4, 2, 471, 381))
        self.userLabel.setText("")
        self.userLabel.setPixmap(QtGui.QPixmap("../Graphics/user.png"))
        self.userLabel.setScaledContents(True)
        self.userLabel.setObjectName("userLabel")
        self.graphics.addTab(self.tab_user, "")
        self.tab_tbs_name = QtWidgets.QWidget()
        self.tab_tbs_name.setObjectName("tab_tbs_name")
        self.tbsWidget = QtWidgets.QWidget(self.tab_tbs_name)
        self.tbsWidget.setGeometry(QtCore.QRect(-1, -1, 441, 381))
        self.tbsWidget.setObjectName("tbsWidget")
        self.tbsLabel = QtWidgets.QLabel(self.tbsWidget)
        self.tbsLabel.setGeometry(QtCore.QRect(0, 0, 451, 381))
        self.tbsLabel.setText("")
        self.tbsLabel.setPixmap(QtGui.QPixmap("../Graphics/tbs.png"))
        self.tbsLabel.setScaledContents(True)
        self.tbsLabel.setObjectName("tbsLabel")
        self.graphics.addTab(self.tab_tbs_name, "")
        self.tab_tb_name = QtWidgets.QWidget()
        self.tab_tb_name.setObjectName("tab_tb_name")
        self.tableWidget_2 = QtWidgets.QWidget(self.tab_tb_name)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 441, 381))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tbLabel = QtWidgets.QLabel(self.tableWidget_2)
        self.tbLabel.setGeometry(QtCore.QRect(0, 0, 441, 381))
        self.tbLabel.setText("")
        self.tbLabel.setPixmap(QtGui.QPixmap("../Graphics/table.png"))
        self.tbLabel.setScaledContents(True)
        self.tbLabel.setObjectName("tbLabel")
        self.graphics.addTab(self.tab_tb_name, "")
        self.tab_owner = QtWidgets.QWidget()
        self.tab_owner.setObjectName("tab_owner")
        self.ownerWidget = QtWidgets.QWidget(self.tab_owner)
        self.ownerWidget.setGeometry(QtCore.QRect(0, 0, 441, 381))
        self.ownerWidget.setObjectName("ownerWidget")
        self.segLabel = QtWidgets.QLabel(self.ownerWidget)
        self.segLabel.setGeometry(QtCore.QRect(0, 0, 441, 381))
        self.segLabel.setText("")
        self.segLabel.setObjectName("segLabel")
        self.graphics.addTab(self.tab_owner, "")
        self.tab_operation = QtWidgets.QWidget()
        self.tab_operation.setObjectName("tab_operation")
        self.operationWidget = QtWidgets.QWidget(self.tab_operation)
        self.operationWidget.setGeometry(QtCore.QRect(0, 0, 441, 381))
        self.operationWidget.setObjectName("operationWidget")
        self.opLabel = QtWidgets.QLabel(self.operationWidget)
        self.opLabel.setGeometry(QtCore.QRect(0, 0, 451, 381))
        self.opLabel.setText("")
        self.opLabel.setObjectName("opLabel")
        self.graphics.addTab(self.tab_operation, "")
        self.tab_date = QtWidgets.QWidget()
        self.tab_date.setObjectName("tab_date")
        self.dateWidget = QtWidgets.QWidget(self.tab_date)
        self.dateWidget.setGeometry(QtCore.QRect(0, 0, 441, 381))
        self.dateWidget.setObjectName("dateWidget")
        self.dateLabel = QtWidgets.QLabel(self.dateWidget)
        self.dateLabel.setGeometry(QtCore.QRect(0, 0, 451, 381))
        self.dateLabel.setText("")
        self.dateLabel.setObjectName("dateLabel")
        self.graphics.addTab(self.tab_date, "")
        self.tab_time = QtWidgets.QWidget()
        self.tab_time.setObjectName("tab_time")
        self.timeWidget = QtWidgets.QWidget(self.tab_time)
        self.timeWidget.setGeometry(QtCore.QRect(0, 0, 441, 381))
        self.timeWidget.setObjectName("timeWidget")
        self.timeLabel = QtWidgets.QLabel(self.timeWidget)
        self.timeLabel.setGeometry(QtCore.QRect(0, 0, 451, 381))
        self.timeLabel.setText("")
        self.timeLabel.setObjectName("timeLabel")
        self.graphics.addTab(self.tab_time, "")
        self.gridLayout_2.addWidget(self.graphics, 1, 3, 1, 3)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 2, 3)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1088, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionRecent = QtWidgets.QAction(MainWindow)
        self.actionRecent.setObjectName("actionRecent")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionSelect_all = QtWidgets.QAction(MainWindow)
        self.actionSelect_all.setObjectName("actionSelect_all")
        self.actionToolbar = QtWidgets.QAction(MainWindow)
        self.actionToolbar.setObjectName("actionToolbar")
        self.actionSteps = QtWidgets.QAction(MainWindow)
        self.actionSteps.setObjectName("actionSteps")
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionUndo)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.graphics.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DB_Patterns"))
        self.groupBox.setTitle(_translate("MainWindow", "DBPatterns"))
        self.search.setText(_translate("MainWindow", "Search"))
        self.chooser.setItemText(0, _translate("MainWindow", "GENERAL"))
        self.chooser.setItemText(1, _translate("MainWindow", "USER_NAME"))
        self.chooser.setItemText(2, _translate("MainWindow", "TABLESPACE_NAME"))
        self.chooser.setItemText(3, _translate("MainWindow", "TABLE_NAME"))
        self.chooser.setItemText(4, _translate("MainWindow", "SEG_OWNER"))
        self.chooser.setItemText(5, _translate("MainWindow", "OPERATION"))
        self.chooser.setItemText(6, _translate("MainWindow", "DATE"))
        self.chooser.setItemText(7, _translate("MainWindow", "TIME"))
        self.loadButton.setText(_translate("MainWindow", "Load data"))
        self.graphics.setTabText(self.graphics.indexOf(self.tab_user), _translate("MainWindow", "USER"))
        self.graphics.setTabText(self.graphics.indexOf(self.tab_tbs_name), _translate("MainWindow", "TABLESPACE"))
        self.graphics.setTabText(self.graphics.indexOf(self.tab_tb_name), _translate("MainWindow", "TABLE"))
        self.graphics.setTabText(self.graphics.indexOf(self.tab_owner), _translate("MainWindow", "SEG_OWNER"))
        self.graphics.setTabText(self.graphics.indexOf(self.tab_operation), _translate("MainWindow", "OPERATION"))
        self.graphics.setTabText(self.graphics.indexOf(self.tab_date), _translate("MainWindow", "DATE"))
        self.graphics.setTabText(self.graphics.indexOf(self.tab_time), _translate("MainWindow", "TIME"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "USER_NAME"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TABLESPACE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TABLE"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SEG_OWNER"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "OPERATION"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "SQL"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SQL_-1"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DATE"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "TIME"))
        self.label.setText(_translate("MainWindow", "    Graphics"))
        self.menuFile.setTitle(_translate("MainWindow", "Init"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExport.setText(_translate("MainWindow", " Export data"))
        self.actionRecent.setText(_translate("MainWindow", "Open Recent"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionConnect.setText(_translate("MainWindow", "Connect to DB"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionSelect_all.setText(_translate("MainWindow", "Select all"))
        self.actionToolbar.setText(_translate("MainWindow", "Toolbar"))
        self.actionSteps.setText(_translate("MainWindow", "StepByStep"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

