

SELECT SUPPLEMENTAL_LOG_DATA_MIN FROM V$DATABASE;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;--

SELECT SUPPLEMENTAL_LOG_DATA_MIN FROM V$DATABASE;

EXECUTE DBMS_LOGMNR.ADD_LOGFILE(-
   LOGFILENAME => 'C:\GO\FlashRecoveryArea\GO\ARCHIVELOG\2018_11_06\O1_MF_1_8_FY3FR6BK_.ARC', -
       OPTIONS => DBMS_LOGMNR.NEW);

--EXECUTE DBMS_LOGMNR.ADD_LOGFILE(-
   --LOGFILENAME => 'C:\GO\FlashRecoveryArea\GO\ARCHIVELOG\2018_11_05\O1_MF_1_11_FY2111C4_.ARC');

EXECUTE DBMS_LOGMNR.START_LOGMNR(OPTIONS => DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG);

SELECT USERNAME, OPERATION, TABLE_NAME, TABLE_SPACE, SEG_OWNER, TIMESTAMP as date_, (XIDUSN || ':' || XIDSLT || ':' || XIDSQN) AS time_, SQL_REDO, sql_undo 
        FROM V$LOGMNR_CONTENTS 
        WHERE username <> 'UNKNOWN' 
        and username <> 'SYS' 
        and table_space <> 'None' 
        and table_space <> 'UNKNOW' 
        and table_name <> 'None';

